# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_datetime', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=512)),
                ('subject', models.TextField(max_length=1024)),
                ('message', models.TextField(max_length=8192)),
            ],
        ),
    ]
