# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170617_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='inserted_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
