# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20170617_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactData',
            new_name='Contact',
        ),
    ]
