# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_datetime', models.DateTimeField(auto_created=True)),
                ('course_name', models.CharField(max_length=256)),
                ('course_id', models.IntegerField()),
                ('video_link', models.URLField()),
                ('video_title', models.CharField(max_length=2048)),
            ],
        ),
    ]
