# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='VideosData',
        ),
    ]
